// Jonathan Decondé - 3196362
package game;

//Game settings
public class GameSettings {
    // Gameplay Options
    public Difficulty difficulty;
    public boolean enableBosses;
    public boolean enableLeveling;
    public boolean enableEvents;
    public boolean enableMimicChests;
    public boolean enablePuzzles;

    // Visual Options
    public boolean enableAsciiArt;
    public boolean enableColors;
    public boolean enableEmojis;
    public int mapWidth;
    public int mapHeight;

    // Screen/Viewport Options
    // POORLY IMPLEMENTED
    // todo: properly implement dynamic viewport sizing based on console size
    public int viewportWidth; // How many map tiles to show horizontally
    public int viewportHeight; // How many map tiles to show vertically
    public int consoleWidth; // Console character width (for HUD/borders)
    public int consoleHeight; // Console character height (total lines)

    // Debug Options
    public boolean debugMode;
    public boolean showCoordinates;
    public boolean showMonsterStats;

    // Defaults
    public GameSettings() {
        this.difficulty = Difficulty.NORMAL;
        this.enableBosses = true;
        this.enableLeveling = true;
        this.enableEvents = true;
        this.enableMimicChests = true;
        this.enablePuzzles = true;

        this.enableAsciiArt = true;
        this.enableColors = true;
        this.enableEmojis = false;
        this.mapWidth = 90;
        this.mapHeight = 55;

        this.viewportWidth = 100;
        this.viewportHeight = 28;
        this.consoleWidth = 120;
        this.consoleHeight = 40;

        this.debugMode = false;
        this.showCoordinates = false;
        this.showMonsterStats = false;
    }

    /**
     * Set viewport dimensions with validation
     * Clamps viewport to not exceed console dimensions
     * 
     * @param width  Desired viewport width (clamped to console width)
     * @param height Desired viewport height (clamped to console height)
     * @return true if values were valid, false if they had to be clamped
     */
    public boolean setViewportSize(int width, int height) {
        if (width <= 0 || height <= 0) {
            System.err.println("[SETTINGS] Invalid viewport size: " + width + "x" + height);
            return false;
        }

        boolean valid = true;

        // Clamp to console dimensions
        if (width > consoleWidth) {
            System.out.println("[SETTINGS] Viewport width clamped to console width: " + consoleWidth);
            width = consoleWidth;
            valid = false;
        }

        if (height > consoleHeight) {
            System.out.println("[SETTINGS] Viewport height clamped to console height: " + consoleHeight);
            height = consoleHeight;
            valid = false;
        }

        this.viewportWidth = width;
        this.viewportHeight = height;
        return valid;
    }

    /**
     * Save screen settings to a config file for persistence
     * Saves viewport and console dimensions to saves/screen_settings.cfg
     * 
     * @return true if save was successful, false otherwise
     */
    public boolean saveScreenSettings() {
        try {
            java.nio.file.Path savePath = java.nio.file.Paths.get("saves");
            if (!java.nio.file.Files.exists(savePath)) {
                java.nio.file.Files.createDirectory(savePath);
            }

            java.nio.file.Path configPath = java.nio.file.Paths.get("saves", "screen_settings.cfg");
            try (java.io.BufferedWriter writer = new java.io.BufferedWriter(
                    new java.io.FileWriter(configPath.toFile()))) {
                writer.write("# JavaRPG Game Settings\n");
                writer.write("# Auto-generated by settings menu\n");
                writer.write("# Last updated: " + java.time.LocalDateTime.now() + "\n");
                writer.write("\n");
                writer.write("# Screen/Viewport Settings\n");
                writer.write("viewportWidth=" + viewportWidth + "\n");
                writer.write("viewportHeight=" + viewportHeight + "\n");
                writer.write("consoleWidth=" + consoleWidth + "\n");
                writer.write("consoleHeight=" + consoleHeight + "\n");
                writer.write("\n");
                writer.write("# Dungeon Generation Settings\n");
                writer.write("mapWidth=" + mapWidth + "\n");
                writer.write("mapHeight=" + mapHeight + "\n");
                return true;
            }
        } catch (java.io.IOException e) {
            System.err.println("[SETTINGS] Failed to save screen settings: " + e.getMessage());
            return false;
        }
    }

    /**
     * Load screen settings from config file
     * Reads viewport and console dimensions from saves/screen_settings.cfg
     * 
     * @return true if settings were loaded successfully, false if file doesn't
     *         exist or error occurred
     */
    public boolean loadScreenSettings() {
        try {
            java.nio.file.Path configPath = java.nio.file.Paths.get("saves", "screen_settings.cfg");
            if (!java.nio.file.Files.exists(configPath)) {
                return false; // File doesn't exist yet, use defaults
            }

            try (java.io.BufferedReader reader = new java.io.BufferedReader(
                    new java.io.FileReader(configPath.toFile()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    line = line.trim();
                    if (line.isEmpty() || line.startsWith("#")) {
                        continue; // Skip comments and empty lines
                    }

                    String[] parts = line.split("=", 2);
                    if (parts.length == 2) {
                        String key = parts[0].trim();
                        String value = parts[1].trim();

                        try {
                            int intValue = Integer.parseInt(value);
                            switch (key) {
                                case "viewportWidth":
                                    this.viewportWidth = intValue;
                                    break;
                                case "viewportHeight":
                                    this.viewportHeight = intValue;
                                    break;
                                case "consoleWidth":
                                    this.consoleWidth = intValue;
                                    break;
                                case "consoleHeight":
                                    this.consoleHeight = intValue;
                                    break;
                                case "mapWidth":
                                    this.mapWidth = Math.max(50, Math.min(200, intValue)); // Clamp to reasonable range
                                    break;
                                case "mapHeight":
                                    this.mapHeight = Math.max(30, Math.min(120, intValue)); // Clamp to reasonable range
                                    break;
                            }
                        } catch (NumberFormatException e) {
                            System.err.println("[SETTINGS] Invalid number format for " + key + ": " + value);
                        }
                    }
                }
                System.out.println("[SETTINGS] Loaded saved screen settings: " + viewportWidth + "x" + viewportHeight);
                return true;
            }
        } catch (java.io.IOException e) {
            System.err.println("[SETTINGS] Failed to load screen settings: " + e.getMessage());
            return false;
        }
    }

    /**
     * Set console dimensions and adjust viewport if needed
     * When console shrinks, viewport shrinks to fit
     * 
     * @param width  Console width in characters
     * @param height Console height in characters
     * @throws IllegalArgumentException if dimensions are not positive
     */
    public void setConsoleDimensions(int width, int height) {
        if (width <= 0 || height <= 0) {
            throw new IllegalArgumentException("Console dimensions must be positive");
        }

        this.consoleWidth = width;
        this.consoleHeight = height;

        // Clamp viewport to new console size
        if (this.viewportWidth > width) {
            System.out.println("[SETTINGS] Adjusted viewport width from " + this.viewportWidth + " to " + width);
            this.viewportWidth = width;
        }
        if (this.viewportHeight > height) {
            System.out.println("[SETTINGS] Adjusted viewport height from " + this.viewportHeight + " to " + height);
            this.viewportHeight = height;
        }
    }

    /**
     * Validate current settings configuration
     * 
     * @return true if all settings are valid, false if there are issues
     */
    public boolean isValid() {
        return viewportWidth > 0 && viewportHeight > 0 &&
                viewportWidth <= consoleWidth &&
                viewportHeight <= consoleHeight &&
                mapWidth >= viewportWidth &&
                mapHeight >= viewportHeight;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("=== GAME SETTINGS ===\n");
        sb.append("Difficulty: ").append(difficulty.displayName).append("\n");
        sb.append("Bosses: ").append(enableBosses ? "ON" : "OFF").append("\n");
        sb.append("Leveling: ").append(enableLeveling ? "ON" : "OFF").append("\n");
        sb.append("Events: ").append(enableEvents ? "ON" : "OFF").append("\n");
        sb.append("Mimic Chests: ").append(enableMimicChests ? "ON" : "OFF").append("\n");
        sb.append("Puzzles: ").append(enablePuzzles ? "ON" : "OFF").append("\n");
        sb.append("ASCII Art: ").append(enableAsciiArt ? "ON" : "OFF").append("\n");
        sb.append("Colors: ").append(enableColors ? "ON" : "OFF").append("\n");
        sb.append("Emojis: ").append(enableEmojis ? "ON" : "OFF").append("\n");
        sb.append("Viewport: ").append(viewportWidth).append("x").append(viewportHeight).append("\n");
        sb.append("Console: ").append(consoleWidth).append("x").append(consoleHeight).append("\n");
        sb.append("Debug Mode: ").append(debugMode ? "ON" : "OFF").append("\n");
        return sb.toString();
    }
}
